name: Prevent Unauthorized LGTM/Approved labels

on:
  pull_request_target:
    types: [opened, synchronize, reopened, labeled, unlabeled]

jobs:
  check_lgtm_approved_authorization:
    if: contains(github.event.pull_request.labels.*.name, 'lgtm') || contains(github.event.pull_request.labels.*.name, 'approved')
    uses: kubermatic/.github/.github/workflows/prevent-unauthorized-lgtm-approved.yml@main
    with:
      pr_number: ${{ github.event.pull_request.number }}
      repository: ${{ github.repository }}
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      pull-requests: write
      contents: read
